# Generated by Django 3.2.12 on 2022-05-05 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='act',
            fields=[
                ('act_id', models.AutoField(primary_key=True, serialize=False)),
                ('act_title', models.CharField(max_length=100, verbose_name='service_type')),
                ('act_details', models.CharField(max_length=1000, verbose_name='service_details')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('Complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('Complaint_subject', models.CharField(max_length=100, verbose_name='subject')),
                ('Complaint_message', models.CharField(max_length=500, verbose_name='message')),
                ('Complaint_date', models.CharField(max_length=100, verbose_name='date')),
                ('incident_date', models.CharField(max_length=100, verbose_name='date')),
                ('incident_type', models.CharField(max_length=100, verbose_name='incident_type')),
                ('Complaint_reply', models.CharField(max_length=500, verbose_name='replay')),
                ('assign_date', models.CharField(max_length=100, verbose_name='date')),
                ('finish_date', models.CharField(max_length=100, verbose_name='date')),
                ('remarks', models.CharField(max_length=500, verbose_name='remarks')),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=100, verbose_name='Name')),
                ('staff_address', models.CharField(max_length=500, verbose_name='Staff_address')),
                ('staff_email', models.EmailField(max_length=200, verbose_name='Staff_email')),
                ('staff_phone', models.CharField(max_length=100, verbose_name='Staff_phone')),
                ('staff_location', models.CharField(default='', max_length=200, verbose_name='Staff_location')),
                ('staff_status', models.CharField(default='', max_length=50, verbose_name='Staff_status')),
                ('designation', models.CharField(default='', max_length=50, verbose_name='designation')),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('g_id', models.AutoField(primary_key=True, serialize=False)),
                ('g_details', models.CharField(max_length=1000, verbose_name='service_details')),
                ('gal_img', models.FileField(max_length=1000, upload_to='images/', verbose_name='news_img')),
            ],
        ),
        migrations.CreateModel(
            name='helpline',
            fields=[
                ('h_id', models.AutoField(primary_key=True, serialize=False)),
                ('h_title', models.CharField(max_length=100, verbose_name='service_type')),
                ('h_details', models.CharField(max_length=1000, verbose_name='service_details')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('logid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, verbose_name='username')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('role', models.CharField(max_length=10, verbose_name='role')),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('news_subject', models.CharField(max_length=100, verbose_name='commi_name')),
                ('news_details', models.CharField(max_length=1000, verbose_name='service_details')),
                ('news_img', models.FileField(max_length=1000, upload_to='images/', verbose_name='news_img')),
            ],
        ),
        migrations.CreateModel(
            name='tips',
            fields=[
                ('tip_id', models.AutoField(primary_key=True, serialize=False)),
                ('tip_safty', models.CharField(max_length=100, verbose_name='service_type')),
                ('tip_details', models.CharField(max_length=1000, verbose_name='service_details')),
            ],
        ),
        migrations.CreateModel(
            name='training',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_subject', models.CharField(max_length=100, verbose_name='subject')),
                ('t_message', models.CharField(max_length=500, verbose_name='message')),
                ('t_date', models.CharField(max_length=100, verbose_name='date')),
                ('t_name', models.CharField(max_length=500, verbose_name='replay')),
                ('resource_person', models.CharField(max_length=500, verbose_name='resource_person')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('User_name', models.CharField(max_length=200, verbose_name='uname')),
                ('User_address', models.CharField(max_length=200, verbose_name='address')),
                ('User_email', models.CharField(max_length=100, verbose_name='email')),
                ('User_phone', models.CharField(max_length=100, verbose_name='phone')),
                ('User_gender', models.CharField(default='', max_length=200, verbose_name='User_gender')),
                ('User_dob', models.CharField(default='', max_length=200, verbose_name='User_dob')),
                ('User_aadhar', models.CharField(default='', max_length=200, verbose_name='User_dob')),
                ('User_state', models.CharField(default='', max_length=200, verbose_name='User_dob')),
                ('User_district', models.CharField(default='', max_length=200, verbose_name='User_dob')),
                ('User_village', models.CharField(default='', max_length=200, verbose_name='User_dob')),
                ('User_status', models.CharField(max_length=200, verbose_name='status')),
                ('Log_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='power.login')),
            ],
        ),
        migrations.CreateModel(
            name='mail',
            fields=[
                ('mail_id', models.AutoField(primary_key=True, serialize=False)),
                ('mail_message', models.CharField(max_length=500, verbose_name='message')),
                ('mail_date', models.CharField(max_length=100, verbose_name='date')),
                ('complaint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='power.complaint')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='power.employee')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='power.user')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='staff_logid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='power.login'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='power.employee'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='power.user'),
        ),
    ]
