# Generated by Django 3.2.12 on 2022-05-08 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_img',
        ),
    ]
